# Generated by Django 5.2.7 on 2026-04-05 11:43

from django.db import migrations, models


def migrate_roles_and_workshop_owners(apps, schema_editor):
    User = apps.get_model('users', 'User')
    Workshop = apps.get_model('users', 'Workshop')

    # Rename existing admin roles to owner before applying the new role choices.
    User.objects.filter(role='admin').update(role='owner')

    workshops = Workshop.objects.all().iterator()

    for workshop in workshops:
        owner_id = workshop.owner_id

        if owner_id:
            User.objects.filter(id=owner_id).exclude(role='owner').update(role='owner')
            User.objects.filter(workshop_id=workshop.id, role='owner').exclude(id=owner_id).update(role='staff')
            continue

        owner_user = User.objects.filter(workshop_id=workshop.id, role='owner').order_by('id').first()
        if not owner_user:
            continue

        workshop.owner_id = owner_user.id
        workshop.save(update_fields=['owner'])
        User.objects.filter(workshop_id=workshop.id, role='owner').exclude(id=owner_user.id).update(role='staff')


def reverse_noop(apps, schema_editor):
    # Keep migration irreversible to avoid role downgrades.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_alter_workshop_phone'),
    ]

    operations = [
        migrations.RunPython(migrate_roles_and_workshop_owners, reverse_noop),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('staff', 'Staff')], default='staff', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(role='owner', workshop__isnull=False), fields=('workshop',), name='unique_owner_per_workshop'),
        ),
    ]
