# Generated by Django 6.0.2 on 2026-02-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_locked_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeIdSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_number', models.IntegerField(default=0)),
            ],
        ),
    ]
