# Generated by Django 6.0.2 on 2026-03-08 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='discription',
            new_name='description',
        ),
    ]
